---
title: "Class Analysis"
output: html_notebook
---

```{r Packages}
library("dplyr")
library("DT")
```

```{r Read Data}
quiz_expand <- readRDS(file = here::here("Data/Generated/Quiz_Expand"))
```

```{r Read Functions}
source(here::here("R/Functions/which_nth.R"))
source(here::here("R/Functions/fill_na.R"))
source(here::here("R/Functions/column_color_DT.R"))
```


What questions did students do well on?  Poor?
What was the most common wrong answer? 
What was the variation in the answers?


```{r Compute Class Variables}
class_summed <- quiz_expand %>%
  group_by(
    Q_Number,
    Q_Type,
    Q_Title,
    Q_Text
  ) %>%
  summarise( # Correct_Answers = sum(Score >= 1),
    Total_Answers = sum(Score >= 0),

    Count_Correct = sum(Score >= 1),

    Percent_Correct = signif((Count_Correct / Total_Answers) * 100, 2),
    
    Proportion_Correct = signif(Count_Correct / Total_Answers,2),

    Correct_Answer = list(unique(Answer[Score >= 1])),

    Most_Wrong_Answer = which.nth(Answer, Score == 0, 1, "names"),

    Count_Most_Wrong = which.nth(Answer, Score == 0, 1, "count"),

    Percent_Most_Wrong = signif((Count_Most_Wrong / Total_Answers) * 100, 2),
    
    Proportion_Most_Wrong = signif(Count_Most_Wrong / Total_Answers,2),

    Count_Other_Wrong = which.nth(Answer, Score == 0, -1, "count"),

    Percent_Other_Wrong = signif((Count_Other_Wrong / Total_Answers) * 100, 2),
    
    Proportion_Other_Wrong = signif(Count_Other_Wrong / Total_Answers,2)
  )

```

If nobody answered correctly, Correct_Answer would be blank.  Could come up in questions with more than one correct answer.  Correct_Answer is also stored as a list in case there are multiple correct answers. 


```{r  Unpack Correct Answer}
class_sep <- class_summed %>%
  mutate(Correct_Answer = fill.na(Correct_Answer)) %>%
  tidyr::unnest(Correct_Answer) %>%
  group_by(Q_Number) %>%
  mutate(cols = paste("Answer", seq_along(Q_Number), sep = ".")) %>%
  tidyr::spread(key = cols, value = Correct_Answer) %>%
  tidyr::unite(starts_with("Answer"),
    col = "Correct_Answer",
    sep = ", "
  )
```

```{r Trim for DT}
class_trim <- class_sep %>% 
  select(Q_Number,
         Q_Text,
         Q_Type,
         Correct_Answer,
         Proportion_Correct,
         Count_Correct,
         Most_Wrong_Answer,
         Proportion_Most_Wrong,
         Count_Most_Wrong,
         Proportion_Other_Wrong,
         Count_Other_Wrong,
         Total_Answers
         )
```


```{r Generate Table}

cnames <- c("#", "Text", "Type", "Answer", "%", "n=", "Answer", "%", "n=", "%", "n=", "n=")

sketch <- htmltools::withTags(table(
  class = "display",
  thead(
    tr(
      th(colspan = 3, "Question"),
      th(colspan = 3, "Correct"),
      th(colspan = 3, "Most Common Wrong"),
      th(colspan = 2, "Other Wrong"),
      th(colspan = 2, "Total")
    ),
    tr(
      lapply(cnames, th)
    )
  )
))


datatable(
  class_trim,
  container = sketch,
  colnames = cnames,
  rownames = FALSE,
  class = "compact",
  options = list(
    autoWidth = TRUE,
    pageLength = 10,
    lengthMenu = list(c(5, 10, 25, -1), c(5, 10, 25, "All")),
    order(list(list("Q_Number", "desc"))),

    columnDefs = list(
      list(
        targets = c(1, 3, 6),
        render = JS(
          "function(data, type, row, meta) {",
          "return type === 'display' && data.length > 30 ?",
          "'<span title=\"' + data + '\">' + data.substr(0, 30) + '...</span>' : data;",
          "}"
        )
      ),
      list(
        className = "dt-center",
        targets = c(0, 2, 4, 5:9)
      ),
      list(
        width = "5%",
        targets = c(4, 5, 7, 8, 9, 10, 11)
      )
    )
  )
) %>%
  formatPercentage(c(5, 8, 10)) %>%
  formatStyle(5,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Proportion_Correct))
  ) %>%
  formatStyle(6,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Count_Correct))
  ) %>%
  formatStyle(8,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Proportion_Most_Wrong, flip = TRUE))
  ) %>%
  formatStyle(9,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Count_Most_Wrong, flip = TRUE))
  ) %>%
  formatStyle(10,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Proportion_Other_Wrong, flip = TRUE))
  ) %>%
  formatStyle(11,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Count_Other_Wrong, flip = TRUE))
  )
  
```
