---
title: "Figures"
output:
  html_document:
    df_print: paged
---


```{r, echo = FALSE}
class_trim <- readRDS(file = here::here("Data/Generated/Class_Trim"))
quiz_expand <- readRDS(file = here::here("Data/Generated/Quiz_Expand"))
```

```{r, echo = FALSE}
library("ggplot2")
library("DT")
```
```{r, echo = FALSE}
source(here::here("R/Functions/column_color_DT.R"))
```

### Class Analysis


```{r Generate Table, echo = FALSE}

cnames <- c("#", "Text", "Type", "Answer", "%", "n=", "Answer", "%", "n=", "%", "n=", "n=")

sketch <- htmltools::withTags(table(
  class = "display",
  thead(
    tr(
      th(colspan = 3, "Question"),
      th(colspan = 3, "Correct"),
      th(colspan = 3, "Most Common Wrong"),
      th(colspan = 2, "Other Wrong"),
      th(colspan = 2, "Total")
    ),
    tr(
      lapply(cnames, th)
    )
  )
))


datatable(
  class_trim,
  container = sketch,
  colnames = cnames,
  rownames = FALSE,
  class = "compact",
  options = list(
    autoWidth = TRUE,
    pageLength = 10,
    lengthMenu = list(c(5, 10, 25, -1), c(5, 10, 25, "All")),
    order(list(list("Q_Number", "desc"))),

    columnDefs = list(
      list(
        targets = c(1, 3, 6),
        render = JS(
          "function(data, type, row, meta) {",
          "return type === 'display' && data.length > 30 ?",
          "'<span title=\"' + data + '\">' + data.substr(0, 30) + '...</span>' : data;",
          "}"
        )
      ),
      list(
        className = "dt-center",
        targets = c(0, 2, 4, 5:9)
      ),
      list(
        width = "5%",
        targets = c(4, 5, 7, 8, 9, 10, 11)
      )
    )
  )
) %>%
  formatPercentage(c(5, 8, 10)) %>%
  formatStyle(5,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Proportion_Correct))
  ) %>%
  formatStyle(6,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Count_Correct))
  ) %>%
  formatStyle(8,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Proportion_Most_Wrong, flip = TRUE))
  ) %>%
  formatStyle(9,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Count_Most_Wrong, flip = TRUE))
  ) %>%
  formatStyle(10,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Proportion_Other_Wrong, flip = TRUE))
  ) %>%
  formatStyle(11,
    backgroundColor = do.call(styleInterval, column_cond_format(class_trim$Count_Other_Wrong, flip = TRUE))
  )
  
```

### Time Analysis

```{r, echo = FALSE}
ggplot(quiz_expand)+
  ggalt::geom_dumbbell(aes(x = Attempt_Start,
                           xend = Attempt_End,
                           y = reorder(Full_Name, Attempt_Start)))+
  labs(x = "Time",
       y = "Student")+
  theme(axis.text.y =element_blank())
```


### Individual Analysis